spring:
  application:
   name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_users_db
    username: postgres
    password: 10835954enoch
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect